### ISSUE TITLE
Initial design for bulk historical processing

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#21]
OPERA SDS needs to process 125 months historical data within 12 months period.
We need to have a tool to automate the processing of bulk historical data in addition to the forward processing. 
PGE to trigger: L2_CSLC_S1 PGE
Data region to cover: North America
Input data: S1 A/B SLC

**Comment by philipjyoon** [comment]
Rough design here:
https://docs.google.com/presentation/d/12TRqtPDq9mjAQBhZMBLAMAnV0pD-hchQy2s7e0Og7fI/edit#slide=id.g15b9eab3860_0_0

**Comment by riverma** [comment]
@philipjyoon @hhlee445 - thanks for making this design an open collaboration. Couple questions from your diagram:
- (Step 1) I don't see the schema for the batch jobs showing any associated granule URIs. How does a batch job map to granules?
- (Step 2b) Why would we ever want to _rerun_ the same batch job?
- (Step 2c) Why would we need to lock the document - are we planning to modify the same batch job document?
- (Step 2e) What happens if a few granules succeed but a few fail? How does that affect the three parameters you've listed of "attempted", "successful", "last_run"?

**Comment by philipjyoon** [comment]
@riverma Thanks for the insightful questions. At a high level this design is to be as simple as possible and rely on existing forward processing infrastructure as much as possible. The batch processing works almost exactly like the forward processing except for the CMR query time parameters logic:

1. Forward processing query runs every 60 minutes and grabs whatever is new in the last 60 mins.
2. This batch design query also runs periodically (not sure what the optimal frequency is yet). But instead of grabbing what's new the past 60 mins, it looks up batch_job index documents to see what timeframe it should use to as the start and end of that time frame.

After figuring out the data time parameter for CMR query, the batch processing works exactly same as forward processing:
1. It submits query job into queue.
2. This query job queries CMR and stores results into the GRQ ES.
3. That triggers download jobs to run
4. And so on.

With this context:

- (Step 1) Batch job maps more to the time periods for querying CMR than the actual granules. If we want to map granules/files to the batch jobs, we can introduce a new field in the GRQ ES index hls_download. Why would we want/need this?
- (Step 2b) The logic stated here has to do with something else. This has to do with the lambda function determining whether or not it should run a query in a given period. Whatever the interval we end up setting up, it won't always be completely precise and we may end up running a second or two ahead or behind. So by using the last run time and current time we can run the exact data intervals.
- (Step 2c) Queries can take a while - and they could take an order (or perhaps two) of magnitude longer if we are processing 10x+ for historical data. In these cases the queries could become the bottleneck so we want the flexibility of running multiple query jobs at once. Again, haven't thought too much about parallelization yet - but it's a placeholder to bring up discussions like you did :)
- (Step 2e) This would work exactly the same as how it's done for forward processing. If we want/need more data processing tracking for historical processing than we do for forward, let me know and we can discuss the requirements and design.

**Comment by philipjyoon** [comment]
Requirement: we should only process data within the "North America" defined as following:

"North America (aka “North America”) = USA, all official 14 US Territories, Canada within 200 km of US border, and all mainland countries from US southern border to and including Panama."
