### ISSUE TITLE
[New Feature]: Add outputs.tf for INT, PST, and OPS  environments

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#321]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

We need to add an outputs.tf file for INT, PST and OPS environments.

**Comment by chrisjrd** [comment]
it is a set of output variables that terraform can create for us. Other frameworks like AWS SAM and AWS CDK have a similar concept. These variables can be referenced in other stacks, but we mainly use them in terraform as an additional mechanism to extract variables (that variables.tf doesn't do in certain situations).

They also serve as additional documentation. Teams use this set of variables to output things like queue names or URLs and things of the sort that terraform knows about at the point of deployment, that would otherwise be cumbersome to get. On other projects, these are used to output things like Lambda names, API Gateway URLs, SQS queue names/URLs, and other outputs of a stack (like a name of all the resources created).

For example, we have terraform code that outputs the MOZART_IP to a text file called `mozart_ip.sh` for use by other scripts. This could be replaced by shell command like `$(terraform output mozart_ip)`. So it can help in automating certain tasks.
