### ISSUE TITLE
[New Feature]: Refactor daac_data_subscriber script 

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#326]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

1. We consolidated the download/extrac/ingest tasks into one job so we won't use the ISL bucket anymore. 
Option -i/--isl-bucket should be removed.
2. -c/--collection-shortname option is not needed with --native-id parameter.

**Comment by riverma** [comment]
+1 as well as updating the documentation wiki for this tool update.

**Comment by philipjyoon** [comment]
It would also be good to break up this file into multiple files. It's now over 1200 lines long and it's hard to navigate. Also we will probably (if we haven't already) started to only modify certain independent sub-functionalities. Such changes would then only affect one or two smaller file instead of one large file multiple times. Merging will get easier.

 One suggestion of break down would be into 4 files:
1. daac_util.py: contains lower-level utility functions
2. daac_query.py: functions/data structures/constants that deal with querying
3. daac_download.py: functions/data structures/constants that deal with downloading
4. daac_data_subscriber.py: main run function and the parser creation

**Comment by riverma** [comment]
Good idea to try and simplify the code @philipjyoon. Would you expect to run any of these Python scripts independently though?

**Comment by philipjyoon** [comment]
@riverma I wouldn't expect to "run" them independently necessarily. More relevant use-case is importing/re-using those smaller files / modules independently as libraries.

For example, right now to create "granules.py" which just prints out the number of granules for some condition, we have to create a copy of daac_data_subscriber.py script and hack it. After refactoring that script this way, we may be able to import daac_util.py and daac_query.py and create granules.py around it without having to carry through / interfering with the entire script.

**Comment by riverma** [comment]
Hi @philipjyoon - sounds reasonable to me! Thanks for the idea in the first place. Two extra questions:
- Does the usage of the original, core script (`daac_data_subscriber.py`) change in any way from the refactor? If so - good to update the usage wiki. 
- Concurrence from other contributors like @maseca?

**Comment by philipjyoon** [comment]
@riverma No. Every functionality and user-interface of the daac_data_subscriber.py code will stay identical (generally the case in re-factoring of code). Only the internal API/data structures will change.

**Comment by philipjyoon** [comment]
(Not to beat a dead horse) Another critical point/goal in refactoring this code is that we are now seeing 2-3 use-cases of this code:
1. Operations (run within a verdi worker)
2. End-to-end testing (--dry-run, --smoke-run, etc)
3. I & T / Regression / Load Testing (survey feature for granules, etc)

Operations is by far the most important so we do not want any new features created for use-cases 2 and 3 to affect use-case 1. By refactoring and then isolating the major business logic of use-case 1 from the others, we can be safer in introducing more needed-features for use-cases 2 and 3.

**Comment by riverma** [comment]
Thanks for the clarification @philipjyoon. That makes a lot of sense to me!
