### ISSUE TITLE
[New Feature]: Nonlinear EC2 ASG target tracking function

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#357]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

When setting the desired number of EC2 instances in each ASG we currently do a 1:1 linear mapping of number_of_jobs_total to desired_instances. There's no damping in setting the number of desired instances. This forces us to set a large MAX ASG values in order to process data with low latency and results in low EC2 machine re-uses which drives up 1) Config cost and 2) EC2 waste when booting up and shutting down. 

### Describe the feature request

Instead we can change that function to be non-linear and introduce damping/compression at the upper end. We can either come up w like a 3rd order polynomial function or just some step function / look up map: Something like: up to 80% of the MAX, we set the desired to be 80% of the number of queued. After that we compress to 1:2 between queued and desired. This should get us a better EC2 instance reusage ratio than the current method.

This would likely require change to this file (there may be others) in hysds code base. But it may be possible to just create OPERA-specific one and not modify the hysds ones.
https://github.com/hysds/hysds/blob/e964f45ddf96fab402a14a5f63aa534a3b650d0a/scripts/sync_ec2_target_tracking_metric.py#L109

**Comment by sjlewis-jpl** [comment]
I believe the goal here is to reduce config costs incurred from bringing up new instances, such as what happens if we process in large bursts.  Instead we want to smooth out the processing load to use a steady number of instances, and minimize the number of new instances that get started.

For R1 and R2 PGEs, we have 12 hours to download granules from the time they're publicly available, and 24 hours to have the resulting OPERA granule available to the DAAC.  We can use some of this time to help smooth out the processing load.  We currently query the DAAC every hour.  We could have the system working to process the results of the queries from, say, 3 hours ago, but using the results of more recent queries to "predict" how many instances to have running.
