### ISSUE TITLE
[New Feature]: Set expiration of logs

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#514]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

We need to set expiration days for the logs generated during the process. Default should be 1 months.  Currently, it never expires so we need to manually delete older logs.

**Comment by philipjyoon** [comment]
Set "retention_in_days" property in the cloud agent config file in main.tf but it's erroring out. This is because due to a bug in the cloud agent: https://github.com/aws/amazon-cloudwatch-agent/issues/554

Fixed here: https://github.com/aws/amazon-cloudwatch-agent/pull/556

We are using version 1.0 and the bug exists in 1.24xxx so we do not have the fixed version. So we can either update cloud agent to the latest so that we can set it properly or call a aws cli command to set that "manually" within the EC2.
